#!/usr/bin/env node
/**
 * Renders every published copy of the architecture diagram, plus the social card,
 * from a single source so they cannot drift.
 *
 *   node scripts/gen-assets.mjs           write the files
 *   node scripts/gen-assets.mjs --check   fail if a committed file is stale
 *
 * Why four copies of one diagram exist
 * ------------------------------------
 * Dark mode inside an SVG (`@media (prefers-color-scheme: dark)`) does work when the
 * SVG is embedded with <img> — but it follows the *operating system*, not the theme
 * toggle of the site showing it. Someone reading GitHub in dark mode on a light OS
 * gets the light diagram on a dark page: transparent artwork disappears, and an
 * opaque white one is a glaring slab. So the colours are not chosen by the SVG:
 *
 *   architecture-light.svg  light palette,  transparent  → GitHub light, via <picture>
 *   architecture-dark.svg   dark palette,   transparent  → GitHub dark,  via <picture>
 *   architecture.svg        dark palette,   own surface  → npm, which strips <picture>
 *   docs/index.md (inline)  no palette at all            → VitePress, via CSS variables
 *
 * <picture> is evaluated against the *page's* colour scheme, which is why GitHub gets
 * it right. npm removes <picture>/<source> when it sanitises the README and keeps the
 * <img>, so that fallback has to stand on its own: it carries its own dark card and no
 * media query, which reads as deliberate on a white page and blends into a dark one.
 *
 * The PNG is rendered here but only its dimensions are verified by --check: text
 * rasterisation differs between machines and fonts, so comparing bytes would make CI
 * fail for reasons that have nothing to do with the diagram.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Resvg } from '@resvg/resvg-js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

const SOURCE = join(root, 'docs', 'assets', 'architecture.source.svg');
const OG_COPY = join(root, 'docs', 'assets', 'og.json');
const PUBLIC = join(root, 'docs', 'public');
const HOME = join(root, 'docs', 'index.md');

const OG_WIDTH = 1280;
const OG_HEIGHT = 640;

const START =
  '<!-- ARCHITECTURE:START — generated by scripts/gen-assets.mjs -->';
const END = '<!-- ARCHITECTURE:END -->';

const banner = (extra) =>
  [
    '<!--',
    '  GENERATED FILE — do not edit by hand.',
    '  Source: docs/assets/architecture.source.svg',
    '  Regenerate with: npm run assets',
    ...(extra ? [`  ${extra}`] : []),
    '-->',
  ].join('\n');

/**
 * Shared by every rendered palette. Only the colours below differ; keeping the
 * geometry rules identical is what makes the three files look like one drawing.
 */
const SHAPES = `
    .node { stroke-width: 1.25; }
    .node-accent { stroke-width: 1.5; }
    .edge { stroke-width: 1.5; fill: none; }
    .edge-accent { stroke-width: 1.75; fill: none; }
    .edge-dashed { stroke-dasharray: 5 4; }
    text { font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "DejaVu Sans", sans-serif; font-size: 13px; }
    .label-title { font-size: 13.5px; font-weight: 600; }
    .label-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "DejaVu Sans Mono", monospace; font-size: 12px; }
    .label-muted { font-size: 11.5px; }`;

/**
 * `.label-muted` is deliberately darker here than the slate-500 the dark palette
 * uses: on the near-white `.node` fill, slate-500 sits just under the 4.5:1 the
 * small type needs.
 */
const LIGHT = `
    .node { fill: #f8fafc; stroke: #94a3b8; }
    .node-accent { fill: rgba(99, 102, 241, 0.12); stroke: #4f46e5; }
    .edge { stroke: #94a3b8; }
    .edge-accent { stroke: #4f46e5; }
    text { fill: #0f172a; }
    .label-muted { fill: #475569; }
    marker path { fill: #94a3b8; stroke: none; }
    marker.accent path { fill: #4f46e5; }`;

const DARK = `
    .node { fill: rgba(148, 163, 184, 0.10); stroke: #64748b; }
    .node-accent { fill: rgba(129, 140, 248, 0.16); stroke: #a5b4fc; }
    .edge { stroke: #64748b; }
    .edge-accent { stroke: #a5b4fc; }
    text { fill: #e2e8f0; }
    .label-muted { fill: #94a3b8; }
    marker path { fill: #64748b; stroke: none; }
    marker.accent path { fill: #a5b4fc; }`;

/** Padding between the artwork and the edge of the fallback's own card. */
const CARD_PAD = 24;
const CARD_SURFACE = `
    .surface { fill: #0f172a; stroke: #1e293b; stroke-width: 1; }`;

/** Splits the source into the parts each output recombines differently. */
function parseSource(svg) {
  const open = svg.match(/<svg\b[^>]*>/);
  if (!open) throw new Error(`no <svg> element in ${SOURCE}`);

  const viewBox = open[0].match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`no viewBox in ${SOURCE}`);

  const [, , w, h] = viewBox.split(/\s+/).map(Number);
  if (!Number.isFinite(w) || !Number.isFinite(h)) {
    throw new Error(`unreadable viewBox "${viewBox}" in ${SOURCE}`);
  }

  const body = svg
    .slice(svg.indexOf(open[0]) + open[0].length, svg.lastIndexOf('</svg>'))
    .replace(/^\n/, '')
    .replace(/\s+$/, '');

  if (/<style\b/.test(body) || /(fill|stroke)="#/.test(body)) {
    throw new Error(
      `${SOURCE} carries its own colours — it must only use the CSS classes, the palette comes from this generator`
    );
  }

  const labelledBy = open[0].match(/aria-labelledby="([^"]+)"/)?.[1];
  return { viewBox, width: w, height: h, body, labelledBy };
}

/** Splits <title>/<desc> off the body: the card variant keeps them unshifted. */
function splitAccessibleNames(body) {
  const names = [];
  const rest = body.replace(/^\s*<(title|desc)\b[\s\S]*?<\/\1>\n?/gm, (m) => {
    names.push(m.trimEnd());
    return '';
  });
  return { names: names.join('\n'), rest: rest.replace(/^\n+/, '') };
}

function standalone({ viewBox, width, height, body, labelledBy }, palette) {
  const { names, rest } = splitAccessibleNames(body);
  return `<?xml version="1.0" encoding="UTF-8"?>
${banner()}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="${width}" height="${height}" role="img"${
    labelledBy ? ` aria-labelledby="${labelledBy}"` : ''
  }>
${names}

  <style>${SHAPES}
${palette}
  </style>

${rest}
</svg>
`;
}

/**
 * The npm fallback. Same drawing as the dark variant, but on a card of its own so it
 * never depends on what colour the surrounding page happens to be.
 */
function carded({ width, height, body, labelledBy }) {
  const { names, rest } = splitAccessibleNames(body);
  const w = width + CARD_PAD * 2;
  const h = height + CARD_PAD * 2;
  const indented = rest.replace(/^(?=.)/gm, '  ');

  return `<?xml version="1.0" encoding="UTF-8"?>
${banner('This copy is what npm shows: it brings its own background on purpose.')}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img"${
    labelledBy ? ` aria-labelledby="${labelledBy}"` : ''
  }>
${names}

  <style>${SHAPES}
${DARK}
${CARD_SURFACE}
  </style>

  <rect class="surface" x="0.5" y="0.5" width="${w - 1}" height="${h - 1}" rx="14" />

  <g transform="translate(${CARD_PAD}, ${CARD_PAD})">
${indented}
  </g>
</svg>
`;
}

/** The VitePress copy: no palette, custom.css drives it from the theme variables. */
function inline({ viewBox, body, labelledBy }) {
  return `<svg viewBox="${viewBox}" role="img"${
    labelledBy ? ` aria-labelledby="${labelledBy}"` : ''
  }>
${body}
</svg>`;
}

const escapeXml = (s) =>
  String(s).replace(
    /[<>&]/g,
    (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;' })[c]
  );

/**
 * Rough advance width for the pill sizing. The renderer gives us no text metrics,
 * and a badge only has to enclose its label with a bit of air, so an estimate that
 * errs wide is entirely adequate — and it keeps the output deterministic.
 */
const textWidth = (text, size) => text.length * size * 0.6;

function ogSvg({ name, tagline, badges, site }) {
  const pills = [];
  let x = 96;
  for (const badge of badges) {
    const w = Math.round(textWidth(badge, 24) + 48);
    pills.push(
      `  <rect class="pill" x="${x}" y="452" width="${w}" height="52" rx="26" />`,
      `  <text class="pill-label" x="${x + w / 2}" y="486" text-anchor="middle">${escapeXml(badge)}</text>`
    );
    x += w + 20;
  }

  const lines = tagline.map(
    (line, i) =>
      `  <text class="tagline" x="96" y="${330 + i * 46}">${escapeXml(line)}</text>`
  );

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${OG_WIDTH} ${OG_HEIGHT}" width="${OG_WIDTH}" height="${OG_HEIGHT}">
  <style>
    text { font-family: Inter, "Fira Sans", "DejaVu Sans", sans-serif; }
    .title { font-size: 72px; font-weight: 700; fill: #e2e8f0; }
    .tagline { font-size: 32px; fill: #94a3b8; }
    .pill { fill: rgba(129, 140, 248, 0.12); stroke: #334155; stroke-width: 1.5; }
    .pill-label { font-size: 24px; fill: #a5b4fc; }
    .site { font-size: 22px; fill: #64748b; }
  </style>

  <rect x="0" y="0" width="${OG_WIDTH}" height="${OG_HEIGHT}" fill="#0f172a" />
  <rect x="0" y="0" width="${OG_WIDTH}" height="6" fill="#4f46e5" />

  <circle cx="70" cy="224" r="12" fill="#a5b4fc" />
  <text class="title" x="96" y="248">${escapeXml(name)}</text>

${lines.join('\n')}

${pills.join('\n')}

  <text class="site" x="${OG_WIDTH - 96}" y="486" text-anchor="end">${escapeXml(site)}</text>
</svg>
`;
}

// ---------------------------------------------------------------- run

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const og = JSON.parse(readFileSync(OG_COPY, 'utf8'));
const site = readFileSync(join(PUBLIC, 'CNAME'), 'utf8').trim();

const source = parseSource(readFileSync(SOURCE, 'utf8'));

const files = new Map([
  [join(PUBLIC, 'architecture-light.svg'), standalone(source, LIGHT)],
  [join(PUBLIC, 'architecture-dark.svg'), standalone(source, DARK)],
  [join(PUBLIC, 'architecture.svg'), carded(source)],
]);

// The home page keeps its own prose; only the block between the markers is ours.
const home = readFileSync(HOME, 'utf8');
const from = home.indexOf(START);
const to = home.indexOf(END);
if (from === -1 || to === -1) {
  throw new Error(`${HOME} is missing the ${START} / ${END} markers`);
}
files.set(
  HOME,
  home.slice(0, from + START.length) +
    '\n' +
    inline(source) +
    '\n' +
    home.slice(to)
);

const pngSvg = ogSvg({
  // og.json may override the heading: a scoped package name reads as
  // "@scope/thing" on npm but the card is titled like the repository.
  name: og.title ?? pkg.name,
  tagline: og.tagline,
  badges: og.badges,
  site,
});

let stale = 0;
for (const [file, content] of files) {
  const shown = relative(root, file);
  let current = null;
  try {
    current = readFileSync(file, 'utf8');
  } catch {
    /* missing counts as stale */
  }
  if (current === content) continue;

  if (check) {
    console.error(`${shown} is out of date — run: npm run assets`);
    stale += 1;
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
    console.log(`wrote ${shown}`);
  }
}

const pngPath = join(PUBLIC, 'og.png');
if (check) {
  // Bytes are not comparable across machines — fonts rasterise differently — so the
  // contract verified here is the one GitHub actually cares about.
  let png;
  try {
    png = readFileSync(pngPath);
  } catch {
    console.error('docs/public/og.png is missing — run: npm run assets');
    process.exit(1);
  }
  // A zero-length or half-written file would throw RangeError out of the top
  // level instead of reaching the message the catch above was written for.
  if (png.length < 24) {
    console.error(
      `docs/public/og.png is ${png.length} bytes — too short to be a PNG. Run: npm run assets`
    );
    process.exit(1);
  }
  const width = png.readUInt32BE(16);
  const height = png.readUInt32BE(20);
  if (width !== OG_WIDTH || height !== OG_HEIGHT) {
    console.error(
      `docs/public/og.png is ${width}x${height}, GitHub's social preview wants ${OG_WIDTH}x${OG_HEIGHT}`
    );
    stale += 1;
  }
  if (png.length >= 1024 * 1024) {
    console.error(
      `docs/public/og.png is ${(png.length / 1024 / 1024).toFixed(2)} MB, GitHub rejects 1 MB and above`
    );
    stale += 1;
  }
  if (stale > 0) process.exit(1);
  console.log('assets are up to date');
} else {
  const png = new Resvg(pngSvg, {
    fitTo: { mode: 'width', value: OG_WIDTH },
    font: { loadSystemFonts: true, defaultFontFamily: 'DejaVu Sans' },
  })
    .render()
    .asPng();
  writeFileSync(pngPath, png);
  console.log(
    `wrote docs/public/og.png (${OG_WIDTH}x${OG_HEIGHT}, ${(png.length / 1024).toFixed(0)} kB)`
  );
}
